-- gopls build-tag awareness — intentionally TAG-NEUTRAL.
--
-- Go files behind a build constraint (`//go:build <tag>`) are invisible
-- to gopls unless that tag is active: gopls logs "no package metadata for
-- file" and InlayHint / references / diagnostics silently fail in them.
-- The fix is `settings.gopls.buildFlags = { "-tags=<a,b,c>" }`.
--
-- Build tags are per-developer / per-repo (one monorepo wants
-- `test,gold,integration`, another wants something else), so this SHARED
-- spec deliberately sets none — baking one project's tags into everyone's
-- config is the wrong default. Add the tags YOUR codebase needs in the
-- gitignored custom layer at `lua/custom/plugins/gopls.lua`:
--
--     return {
--       {
--         "neovim/nvim-lspconfig",
--         opts = function(_, opts)
--           local servers = opts.servers or {}
--           opts.servers = servers
--           servers.gopls = servers.gopls or {}
--           servers.gopls.settings = servers.gopls.settings or {}
--           servers.gopls.settings.gopls = servers.gopls.settings.gopls or {}
--           servers.gopls.settings.gopls.buildFlags = { "-tags=integration,gold" }
--         end,
--       },
--     }
--
-- FUNCTION form on purpose: lazy.nvim CONCATENATES list-valued `opts`
-- across spec fragments, so a table `buildFlags = {...}` in a second
-- fragment would append a duplicate `-tags=` flag instead of replacing.
-- worktree.nvim restarts gopls on worktree-switch, so the override
-- re-applies automatically.
--
-- (The `/go-test-env` skill can scaffold this file for you — pick the
-- `lsp` target.)
return {}